import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    'nav.dashboard': 'DASHBOARD',
    'nav.members': 'MEMBERS',
    'nav.tournaments': 'TOURNAMENTS',
    'nav.slamPoetry': 'SLAM POETRY?',
    'nav.features': 'FEATURES',
    'nav.howItWorks': 'HOW IT WORKS',
    'nav.collectives': 'COLLECTIVES',
    'nav.login': 'LOGIN',
    'nav.signup': 'Create Account',
    'nav.myProfile': 'My Profile',
    'nav.logout': 'Logout',
    'nav.loggingOut': 'Logging out...',
    'nav.logoutConfirm': 'Are you sure you want to logout?',
    'nav.cancel': 'Cancel',
    'nav.logoutTitle': 'Logout',
    
    // Hero
    'hero.platform': 'The slam poetry collective platform',
    'hero.title': 'MANAGE YOUR',
    'hero.title1': 'WORDS.',
    'hero.title2': 'YOUR STAGES.',
    'hero.title3': 'YOUR POETS.',
    'hero.description': 'Slam Net is the platform dedicated to slam poetry collectives — manage your members, organize tournaments, draw passages and follow rankings in real time.',
    'hero.createCollective': 'CREATE MY COLLECTIVE',
    'hero.watchDemo': 'WATCH A DEMO',
    'hero.liveRanking': 'LIVE RANKING',
    'hero.tournamentInProgress': 'TOURNAMENT IN PROGRESS',
    'hero.explore': 'EXPLORE',
    
    // Features
    'features': 'FEATURES',
    'features.title': 'EVERYTHING YOUR',
    'features.title1': 'COLLECTIVE',
    'features.title2': 'NEEDS.',
    'features.description': 'A single platform to manage the life of your slam collective — from members to podiums, through every verse spoken on stage.',
    'feature01.title': 'MEMBER MANAGEMENT',
    'feature01.description': 'Register each poet of your collective — name, contact, biography, performance history. A complete directory, always at hand.',
    'feature01.detail': 'Detailed profiles · History · Status',
    'feature02.title': 'ORGANIZED TOURNAMENTS',
    'feature02.description': 'Create tournaments, set rules, manage registrations — collective members or external guests. Every event, from A to Z.',
    'feature02.detail': 'Multi-rounds · Guests · Online registration',
    'feature03.title': 'RANDOM DRAW',
    'feature03.description': 'The automatic draw decides the order of passage for each round. Transparent, impartial, without friction.',
    'feature03.detail': 'Certified random · Round by round · PDF export',
    'feature04.title': 'SCORES & RANKINGS',
    'feature04.description': 'Enter jury scores live. Rankings update instantly. The stage knows its champion as soon as the last score falls.',
    'feature04.detail': 'Real-time scores · Multiple juries · Podium',
    
    // How it works
    'howItWorks': 'HOW IT WORKS',
    'howItWorks.title': 'FROM COLLECTIVE',
    'howItWorks.title1': 'TO PODIUM',
    'howItWorks.title2': 'IN 6 STEPS.',
    'step01.title': 'Create your collective',
    'step01.description': 'Sign up in 2 minutes, name your collective and start inviting your poets.',
    'step02.title': 'Register your members',
    'step02.description': 'Add each slammer with their complete profile. They can also join via an invitation link.',
    'step03.title': 'Launch a tournament',
    'step03.description': 'Create a tournament, define rounds, open registrations to members and guests.',
    'step04.title': 'Draw & passages',
    'step04.description': 'Trigger the draw. The order of passage is automatically generated for each round.',
    'step05.title': 'Enter scores',
    'step05.description': 'Each juror scores live. The system calculates averages and updates the ranking.',
    'step06.title': 'Crown the champion',
    'step06.description': 'The final ranking is established. Share the podium, archive the event.',
    
    // CTA
    'cta.freeToStart': 'FREE TO START',
    'cta.title': 'YOUR COLLECTIVE',
    'cta.title1': 'DESERVES A',
    'cta.title2': 'REAL STAGE.',
    'cta.description': 'Join the slam collectives that organize their events with Slam Net. Free registration, no card required.',
    'cta.createFreeAccount': 'CREATE FREE ACCOUNT',
    
    // Auth modals
    'auth.login': 'LOGIN',
    'auth.signup': 'SIGNUP',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signIn': 'Sign in',
    'auth.signingIn': 'Signing in...',
    'auth.createAccount': 'Create my account',
    'auth.creatingAccount': 'Creating account...',
    'auth.collectiveName': 'Collective name',
    'auth.collectiveNamePlaceholder': 'Your collective name',
    'auth.city': 'City',
    'auth.cityPlaceholder': 'Your city',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.signUp': 'Sign up',
    'auth.loginLink': 'Login',
    'auth.emailPasswordRequired': 'Email and password required',
    'auth.invalidEmail': 'Invalid email format',
    'auth.allFieldsRequired': 'All fields must be filled',
    'auth.passwordMinLength': 'Password must contain at least 6 characters',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.loginSuccess': 'Login successful',
    'auth.signupSuccess': 'Account created successfully',
    'auth.loginError': 'Error during login',
    'auth.signupError': 'Error during signup',
    'auth.loggingIn': 'Logging in...',
    
    // Footer
    'footer.copyright': '© 2026 SLAM NET · ALL RIGHTS RESERVED',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.contact': 'Contact',
    
    // Privacy page
    'privacy.title': 'PRIVACY',
    'privacy.dataCollection.title': 'Data Collection',
    'privacy.dataCollection.description': 'Slam Net collects only the data necessary for the platform to function, including account information, collective data, and performance statistics.',
    'privacy.dataUsage.title': 'Data Usage',
    'privacy.dataUsage.description': 'Your data is used to allow you to manage your collective, organize tournaments, and track poet performances. We do not sell your data to third parties.',
    'privacy.hosting.title': 'Hosting',
    'privacy.hosting.description': 'All your data is hosted on servers located in France, in compliance with European data protection regulations (GDPR).',
    'privacy.yourRights.title': 'Your Rights',
    'privacy.yourRights.description': 'You have the right to access, modify, and delete your personal data at any time. Contact us to exercise these rights.',
    
    // Terms page
    'terms.title': 'TERMS AND CONDITIONS',
    'terms.platformUsage.title': 'Platform Usage',
    'terms.platformUsage.description': 'Slam Net is intended for slam poetry collectives to organize events and manage their members. Any abusive or fraudulent use will result in account deletion.',
    'terms.liability.title': 'Liability',
    'terms.liability.description': 'Slam Net cannot be held responsible for direct or indirect damages resulting from the use of the platform. Users are responsible for the content they publish.',
    'terms.intellectualProperty.title': 'Intellectual Property',
    'terms.intellectualProperty.description': 'Original creations (poems, texts, performances) remain the property of their authors. Slam Net claims no rights over user-created content.',
    'terms.modification.title': 'Modification of Conditions',
    'terms.modification.description': 'Slam Net reserves the right to modify these terms and conditions at any time. Users will be informed of significant changes.',
    
    // Contact page
    'contact.title': 'CONTACT',
    'contact.email.title': 'Email',
    'contact.phone.title': 'Phone',
    'contact.address.title': 'Address',
    
    // Dashboard
    'dashboard.title': 'DASHBOARD',
    'dashboard.needLogin': 'You must be logged in to access this page',
    'dashboard.members': 'Members',
    'dashboard.tournaments': 'Tournaments',
    'dashboard.performances': 'Performances',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.organizeTournament': 'Organize a new tournament',
    'dashboard.organizeTournamentDesc': 'Create and configure a tournament',
    'dashboard.inviteMember': 'Invite a member',
    'dashboard.inviteMemberDesc': 'Add a new poet to the collective',
    'dashboard.viewStats': 'View statistics',
    'dashboard.viewStatsDesc': 'Detailed collective analytics',
    'dashboard.activeTournaments': 'Active Tournaments',
    'dashboard.noActiveTournaments': 'No active tournaments',
    
    // Membres
    'membres.title': 'MEMBERS',
    'membres.subtitle': 'OUR POETS.',
    'membres.description': 'Manage your collective members',
    'membres.addMember': 'Add a member',
    'membres.search': 'Search for a member...',
    'membres.loading': 'Loading...',
    'membres.noMembers': 'No members in your collective',
    'membres.noMembersFound': 'No members found',
    'membres.addFirstMember': 'Add your first member',
    'membres.deleteSuccess': 'Member deleted successfully',
    'membres.deleteError': 'Error deleting member',
    'membres.bornOn': 'Born on',
    
    // Tournois
    'tournois.title': 'TOURNAMENTS',
    'tournois.subtitle': 'OUR TOURNAMENTS.',
    'tournois.description': 'Manage your collective tournaments',
    'tournois.addTournament': 'Add a tournament',
    'tournois.loading': 'Loading tournaments...',
    'tournois.needLogin': 'You must be logged in to access this page',
    'tournois.noTournament': 'No tournaments',
    'tournois.noTournamentDesc': 'You haven\'t created any tournaments yet. Start by organizing your first event!',
    'tournois.createTournament': 'Create a tournament',
    'tournois.createSuccess': 'Tournament created successfully',
    'tournois.updateSuccess': 'Tournament modified successfully',
    'tournois.deleteSuccess': 'Tournament deleted successfully',
    'tournois.deleteError': 'Error deleting tournament',
    'tournois.manage': 'Manage the tournament',
    'tournois.manageShort': 'Manage',
    'tournois.juror': 'juror',
    'tournois.jurors': 'jurors',
    
    // Common buttons and actions
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.save': 'Save',
    'common.creating': 'Creating...',
    'common.updating': 'Updating...',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.stageName': 'Stage name',
    'common.add': 'Add',
    'common.addPhoto': 'Add',
    'common.loading': 'Loading...',
    'common.loadingInfo': 'Loading information...',
    
    // Create Member Dialog
    'createMember.title': 'New member',
    'createMember.lastName': 'Last name *',
    'createMember.firstName': 'First name *',
    'createMember.pseudo': 'Pseudo *',
    'createMember.email': 'Email *',
    'createMember.dateOfBirth': 'Date of birth *',
    'createMember.address': 'Address *',
    'createMember.createdSuccess': 'Member created successfully',
    'createMember.createError': 'Error creating member',
    
    // Update Member Dialog
    'updateMember.title': 'Update member',
    'updateMember.lastName': 'Last name',
    'updateMember.firstName': 'First name',
    'updateMember.pseudo': 'Pseudo',
    'updateMember.email': 'Email',
    'updateMember.dateOfBirth': 'Date of birth',
    'updateMember.address': 'Address',
    'updateMember.preview': 'Preview',
    'updateMember.photoUploadSuccess': 'Photo uploaded successfully',
    'updateMember.photoUploadError': 'Error uploading photo',
    'updateMember.loadingInfo': 'Loading information...',
    'updateMember.updatedSuccess': 'Member updated successfully',
    'updateMember.updateError': 'Error updating member',
    
    // Create Tournament Dialog
    'createTournoi.title': 'New tournament',
    'createTournoi.name': 'Tournament name *',
    'createTournoi.namePlaceholder': 'Ex: Grand Slam de Paris',
    'createTournoi.location': 'Location *',
    'createTournoi.locationPlaceholder': 'Ex: Café de la Gare',
    'createTournoi.date': 'Date *',
    'createTournoi.time': 'Time *',
    'createTournoi.juryCount': 'Number of jurors *',
    'createTournoi.duration': 'Duration per performance (optional)',
    'createTournoi.durationFormat': 'Format: minutes:seconds (ex: 3:00)',
    'createTournoi.enableDraw': 'Enable random draw of participants',
    'createTournoi.posterUrl': 'Poster URL (optional)',
    'createTournoi.posterPlaceholder': 'https://example.com/poster.jpg',
    'createTournoi.allFieldsRequired': 'All required fields must be filled',
    'createTournoi.minJuryError': 'The number of jurors must be at least 1',
    'createTournoi.createError': 'Error creating tournament',
    'createTournoi.min': 'Min',
    'createTournoi.sec': 'Sec',
    
    // Delete dialogs
    'deleteMember.title': 'Delete member',
    'deleteMember.message': 'Are you sure you want to delete this member? This action is irreversible.',
    'deleteTournoi.title': 'Delete tournament',
    'deleteTournoi.message': 'Are you sure you want to delete the tournament "{name}"? This action is irreversible.',
    
    // Tournoi Gestion Layout
    'tournoiGestion.tournament': 'TOURNAMENT',
    'tournoiGestion.loading': 'Loading tournament...',
    'tournoiGestion.notFound': 'Tournament not found',
    'tournoiGestion.backToTournois': 'Back to tournaments',
    'tournoiGestion.menu': 'Menu',
    'tournoiGestion.closeMenu': 'Close menu',
    'tournoiGestion.participants': 'Participants',
    'tournoiGestion.performances': 'Performances',
    'tournoiGestion.ranking': 'Ranking',
    'tournoiGestion.settings': 'Settings',
    
    // Tournoi Participants
    'tournoiParticipants.title': 'Participants',
    'tournoiParticipants.addParticipant': 'Add a participant',
    'tournoiParticipants.loading': 'Loading participants...',
    'tournoiParticipants.noParticipants': 'No participants yet',
    'tournoiParticipants.loadingError': 'Error loading participants',
    'tournoiParticipants.removeSuccess': 'Participant removed successfully',
    'tournoiParticipants.removeError': 'Error removing participant',
    'tournoiParticipants.removeTitle': 'Remove participant',
    'tournoiParticipants.removeMessage': 'Are you sure you want to remove this participant from the tournament?',
    'tournoiParticipants.remove': 'Remove',
    'tournoiParticipants.member': 'Member',
    'tournoiParticipants.guest': 'Guest',
    'tournoiParticipants.delete': 'Delete',
    
    // Add Participant Dialog
    'addParticipant.title': 'Add participants',
    'addParticipant.membersTab': 'Collective members',
    'addParticipant.guestsTab': 'Guest',
    'addParticipant.searchMember': 'Search for a member...',
    'addParticipant.noMemberFound': 'No members found',
    'addParticipant.noMemberAvailable': 'No members available',
    'addParticipant.membersCount': 'members',
    'addParticipant.inscribed': 'inscribed',
    'addParticipant.pseudo': 'Pseudo',
    'addParticipant.pseudoRequired': 'Pseudo is required',
    'addParticipant.selectMember': 'Please select a member',
    'addParticipant.alreadyInscribed': 'This member is already registered for the tournament',
    'addParticipant.loadingMembers': 'Error loading members',
    'addParticipant.registering': 'Registering...',
    'addParticipant.register': 'Register',
    'addParticipant.memberInscribed': 'Inscribed',
    'addParticipant.finish': 'Finish',
    'addParticipant.registerSuccess': 'Member registered to tournament successfully',
    'addParticipant.registerError': 'Error registering to tournament',
    'addParticipant.guestPlaceholder': 'Enter guest pseudo',
    'addParticipant.guestSuccess': 'Guest registered to tournament successfully',
    'addParticipant.guestError': 'Error registering guest',
    
    // Tournoi Performances
    'tournoiPerformances.title': 'Performances',
    'tournoiPerformances.addPerformance': 'Add a performance',
    'tournoiPerformances.loading': 'Loading performances...',
    'tournoiPerformances.noPerformances': 'No performances yet',
    'tournoiPerformances.deleteTitle': 'Delete performance',
    'tournoiPerformances.deleteMessage': 'Are you sure you want to delete this performance?',
    'tournoiPerformances.createSuccess': 'Performance created successfully',
    'tournoiPerformances.createError': 'Error creating performance',
    'tournoiPerformances.deleteSuccess': 'Performance deleted successfully',
    'tournoiPerformances.deleteError': 'Error deleting performance',
    'tournoiPerformances.terminatedSuccess': 'Performance completed successfully',
    'tournoiPerformances.terminateError': 'Error completing performance',
    'tournoiPerformances.selectParticipant': 'Please select a participant',
    'tournoiPerformances.participantNotFound': 'Participant not found',
    'tournoiPerformances.noPerformanceSelected': 'No performance selected',
    'tournoiPerformances.mustBeTerminated': 'This performance must be completed before adding notes',
    'tournoiPerformances.selectTerminated': 'Select a completed performance to add notes',
    'tournoiPerformances.invalidNote': 'Value must be a number between 0 and 10',
    'tournoiPerformances.notesRequired': 'You must add exactly {nb} notes (number of juries)',
    'tournoiPerformances.notesSaved': 'Notes saved successfully',
    'tournoiPerformances.saveError': 'Error saving notes',
    'tournoiPerformances.noteUpdated': 'Note updated successfully',
    'tournoiPerformances.updateNoteError': 'Error updating note',
    'tournoiPerformances.loadingPerformances': 'Error loading performances',
    'tournoiPerformances.loadingParticipants': 'Error loading participants',
    'tournoiPerformances.createPerformance': 'Create performance',
    'tournoiPerformances.cancel': 'Cancel',
    'tournoiPerformances.create': 'Create',
    'tournoiPerformances.start': 'Start',
    'tournoiPerformances.play': 'Play',
    'tournoiPerformances.pause': 'Pause',
    'tournoiPerformances.finish': 'Finish',
    'tournoiPerformances.recording': 'Recording...',
    'tournoiPerformances.duration': 'Duration',
    'tournoiPerformances.score': 'Score',
    'tournoiPerformances.timer': 'Timer',
    'tournoiPerformances.noCurrentPerformance': 'No performance in progress',
    'tournoiPerformances.addNotes': 'Add notes and penalties',
    'tournoiPerformances.notes': 'Notes',
    'tournoiPerformances.penalties': 'Penalties',
    'tournoiPerformances.notePlaceholder': 'Note (ex: 8,5)',
    'tournoiPerformances.penaltyPlaceholder': 'Penalty (ex: 1,5)',
    'tournoiPerformances.add': 'Add',
    'tournoiPerformances.notesToRecord': 'Notes to record',
    'tournoiPerformances.penaltiesToRecord': 'Penalties to record',
    'tournoiPerformances.maxNotesReached': 'Maximum number of notes reached ({nb} juries)',
    'tournoiPerformances.remove': 'Remove',
    'tournoiPerformances.restore': 'Restore',
    'tournoiPerformances.save': 'Save',
    'tournoiPerformances.existingNotes': 'Existing notes and penalties',
    'tournoiPerformances.listTab': 'List',
    'tournoiPerformances.inProgressTab': 'In Progress',
    'tournoiPerformances.notesTab': 'Notes',
    'tournoiPerformances.draw': 'Draw',
    'tournoiPerformances.ready': 'Ready',
    'tournoiPerformances.inProgress': 'In Progress',
    'tournoiPerformances.paused': 'Paused',
    'tournoiPerformances.completed': 'Completed',
    'tournoiPerformances.notDefined': 'Not defined',
    'tournoiPerformances.participant': 'Participant',
    'tournoiPerformances.unknown': 'Unknown',
    'tournoiPerformances.drawing': 'Drawing...',
    'tournoiPerformances.winnerSelected': 'PARTICIPANT SELECTED!',
    'tournoiPerformances.spin': 'Spin the roulette',
    'tournoiPerformances.goodLuck': 'Good luck to all!',
    'tournoiPerformances.availableCount': 'Available participants',
    'tournoiPerformances.currentMax': 'Current max performances',
    'tournoiPerformances.nextRoundReady': 'Next round ready!',
    'tournoiPerformances.allParticipantsEqual': 'All participants have the same number of performances',
    'tournoiPerformances.allHavePerformances': 'Each has {count} performance(s)',
    'tournoiPerformances.startNextRound': 'Start next round',
    'tournoiPerformances.lastParticipant': 'Last available participant!',
    'tournoiPerformances.confirm': 'Confirm creation',
    'tournoiPerformances.redraw': 'Redraw',
    
    // Tournoi Classement
    'tournoiClassement.title': 'Ranking',
    'tournoiClassement.loading': 'Loading ranking...',
    'tournoiClassement.noRanking': 'No ranking yet',
    'tournoiClassement.summary': 'Summary',
    'tournoiClassement.participants': 'Participants',
    'tournoiClassement.average': 'Average',
    'tournoiClassement.maxRounds': 'Max rounds',
     'tournoiClassement.loadingError': 'Error loading data',
     
     // Statistics
     'statistics.title': 'Statistics',
     'statistics.loading': 'Loading statistics...',
     'statistics.participantStats.title': 'Participant Statistics',
     'statistics.participantStats.analysis': 'Performance Analysis',
    'statistics.participantStats.details': 'Round Details',
    'statistics.participantStats.notes': 'Notes',
     'statistics.participantStats.penalties': 'Penalties',
     'statistics.participantStats.scoreEvolution': 'Score Evolution',
     'statistics.participantStats.scoreVsAverage': 'Score vs Jury Average',
      'statistics.participantStats.penaltiesByRound': 'Penalties by Round',
      'statistics.participantStats.noNotes': 'No notes',
      'statistics.participantStats.noPerformances': 'No performances recorded',
      'statistics.participantStats.rounds': 'Rounds',
      'statistics.participantStats.totalPoints': 'Total Points',
      'statistics.participantStats.average': 'Average',
      'statistics.participantStats.best': 'Best',
      'statistics.globalStats.title': 'Global Statistics',
     'statistics.globalStats.tournaments': 'Tournaments',
     'statistics.globalStats.performances': 'Performances',
     'statistics.globalStats.totalPoints': 'Total Points',
     'statistics.globalStats.globalAverage': 'Global Average',
     'statistics.globalStats.analysis': 'Performance Analysis',
     'statistics.globalStats.tournamentComparison': 'Tournament Comparison',
     'statistics.globalStats.scoreDistribution': 'Performance Distribution',
     'statistics.globalStats.consistency': 'Consistency Rate',
     'statistics.globalStats.standardDeviation': 'Standard Deviation',
     'statistics.globalStats.performanceHistory': 'Tournament History',
     'statistics.globalStats.excellent': 'Excellent (>8)',
     'statistics.globalStats.good': 'Good (6-8)',
     'statistics.globalStats.average': 'Average (<6)',
     'statistics.globalStats.meanEvolution': 'Average Evolution by Tournament',
     'statistics.globalStats.noTournaments': 'No tournaments recorded',
     'statistics.globalStats.bestPerformance': 'Best Performance',
     'statistics.globalStats.worstPerformance': 'Worst Performance',
     'statistics.globalStats.total': 'Total',
     'statistics.globalStats.best': 'Best',
     'statistics.memberProfile.loading': 'Loading member...',
     'statistics.memberProfile.notFound': 'Member not found',
     'statistics.memberProfile.backToMembers': 'Back to Members',
     'statistics.memberProfile.viewProfile': 'View Profile',
    
    // Tournoi Paramètres
    'tournoiParametres.title': 'Tournament settings',
    'tournoiParametres.durationSection': 'Performance duration',
    'tournoiParametres.maxDurationLabel': 'Maximum duration per performance (min:sec)',
    'tournoiParametres.durationPlaceholder': '03:00',
    'tournoiParametres.durationFormat': 'Expected format: min:sec (ex: 03:00 for 3 minutes)',
    'tournoiParametres.jurySection': 'Jury',
    'tournoiParametres.juryCountLabel': 'Number of jury members',
    'tournoiParametres.juryCountDescription': 'Number of jurors who will score each performance',
    'tournoiParametres.drawSection': 'Draw',
    'tournoiParametres.enableDraw': 'Enable draw',
    'tournoiParametres.enableDrawDescription': 'Allows randomly selecting participant when creating a performance',
    'tournoiParametres.saving': 'Saving...',
    'tournoiParametres.save': 'Save',
    'tournoiParametres.updateSuccess': 'Settings updated successfully',
    'tournoiParametres.updateError': 'Error updating settings',
    
    // Slam Poetry
    'slamPoetry.title': 'SLAM POETRY?',
    'slamPoetry.whatsTitle': 'What is Slam?',
    'slamPoetry.whatsP1': 'A slam is, historically, a poetry competition. It is poetry declaimed in public spaces (on the street, in a bar...) or in a performance venue (in a concert hall, a theater...), with or without musical accompaniment. Slam belongs to the genre of engaged poetry, of which it renews the codes.',
    'slamPoetry.whatsP2': 'The vocabulary is familiar (slang, verlan, neologisms) and the choice of words serves the rhythm. Wordplay and sound play are frequent (paronyms, rhymes, synonyms).',
    'slamPoetry.whatsP3': 'Slam sits between diction and song. The possible instrumental part serves the text and does not cover it. Instruments are few and accompany the voice.',
    'slamPoetry.historyTitle': 'History',
    'slamPoetry.historyP1': 'Born from an idea by American poet Marc Smith, in 1986, slam aims to make poetry readings both less elitist and less boring. Slam provides minimal rules, leaving great freedom to poets within these basic rules.',
    'slamPoetry.historyP2': 'The first European slam events appeared in 1993. In France, slam as a specific genre or scene only appeared in the 1990s, and more specifically in 1995 with the gathering of a core group (Nada, Joël Barazer, MC Clean, Pilote le Hot) mixing poets and "performers" in a bar in Pigalle, rue André Antoine – the Club-Club.',
    'slamPoetry.historyP3': 'In 2006, "Midi 20", the first spoken word album by Grand Corps Malade, a slamer several times winner of Bouchazoreill\'slam tournaments, brought additional spotlight to the French movement.',
    'slamPoetry.historyP4': 'In 2009, under the impetus of various French associations, "La Ligue Slam de France" was formed. Grand Corps Malade is its honorary member and Marc Smith has supported it since its creation. In 2020, the League federates more than 50 associations throughout France.',
    'slamPoetry.rulesTitle': 'Slam Rules',
    'slamPoetry.rulesIntro': 'Even if slam poetry is often described as a means of freedom of expression, the show is structured by rules that are generally as follows:',
    'slamPoetry.rule1': 'Inscriptions are open to all via the presenter',
    'slamPoetry.rule2': 'You can perform alone or in a group',
    'slamPoetry.rule3': 'The text must be original, i.e., written by the slamer himself',
    'slamPoetry.rule4': 'The duration of the performance is generally limited to 3 minutes',
    'slamPoetry.rule5': 'Use of accessories (costumes, musical instruments, sets) is not allowed',
    'slamPoetry.rule6': 'Spectators form a jury that scores each performance',
    'slamPoetry.rule7': 'The highest and lowest scores are often eliminated',
    'slamPoetry.rule8': 'Slammers are scored on different criteria: writing, interpretation, and connection with the audience',
    'slamPoetry.valuesTitle': 'Slam Values',
    'slamPoetry.valuesP1': 'Slam is a form of poetry reading considered as a movement of popular expression, initially on the margins of traditional artistic circuits, today widely recognized and media-covered.',
    'slamPoetry.valuesP2': 'It is an oral and scenic performance art, focused on the word and raw expression with great economy of means, a link between writing and performance.',
    'slamPoetry.valuesP3': 'If poets, particularly from the hip-hop movement, claim it as originating from the street like rap in its beginnings, it is nevertheless practiced by poets of all styles, from all social backgrounds, in the city as in the countryside.',
    'slamPoetry.valuesP4': 'Marc Smith will have relaunched poetic speech in the public square and on a planetary scale. It is now up to everyone to have the words to say themselves.',
    'slamPoetry.worldTitle': 'Slam around the world',
    'slamPoetry.worldIntro': 'Slam has developed in many francophone and non-francophone countries:',
    'slamPoetry.worldFrance': '<strong>France:</strong> The movement is particularly active with the Ligue Slam de France, the Grand Slam National, and the World Slam Cup.',
    'slamPoetry.worldBelgium': '<strong>Belgium:</strong> The first platforms appeared in 2001 in Brussels, with permanent scenes in Mons, Namur and Charleroi.',
    'slamPoetry.worldSwitzerland': '<strong>French-speaking Switzerland:</strong> Slam appeared in 2002 in Geneva, with scenes in Lausanne, Fribourg and Neuchâtel.',
    'slamPoetry.worldQuebec': '<strong>Quebec:</strong> The slam scene proper was born in 2006 with Slamontréal evenings in Montreal.',
    'slamPoetry.worldIndianOcean': '<strong>Indian Ocean:</strong> Slam was introduced in 2002 by Stefan Hart de Keating, first in Mauritius, then in Reunion, Madagascar, Mayotte and Rodrigues.',
    
    // Profile
    'profile.title': 'PROFILE',
    'profile.myProfile': 'MY PROFILE.',
    'profile.description': 'Manage your collective information',
    'profile.mustBeLoggedIn': 'You must be logged in to access this page',
    'profile.loadingError': 'Profile loading error',
    'profile.edit': 'Edit',
    'profile.uploadInProgress': 'Upload in progress...',
    'profile.collectiveName': 'Collective name',
    'profile.city': 'City',
    'profile.email': 'Email',
    'profile.cancel': 'Cancel',
    'profile.saving': 'Saving...',
    'profile.save': 'Save',
    'profile.memberSince': 'Member since',
    'profile.photoUpdated': 'Photo updated successfully',
    'profile.photoUploadError': 'Error uploading photo',
    'profile.updated': 'Profile updated successfully',
    'profile.updateError': 'Error updating profile',
    'profile.uploadError': 'Error during upload',
  },
  fr: {
    // Navbar
    'nav.dashboard': 'DASHBOARD',
    'nav.members': 'MEMBRES',
    'nav.tournaments': 'TOURNOIS',
    'nav.slamPoetry': 'SLAM POÉSIE ?',
    'nav.features': 'FONCTIONNALITÉS',
    'nav.howItWorks': 'COMMENT ÇA MARCHE',
    'nav.collectives': 'COLLECTIFS',
    'nav.login': 'CONNEXION',
    'nav.signup': 'CRÉER UN COMPTE',
    'nav.myProfile': 'Mon profil',
    'nav.logout': 'Déconnexion',
    'nav.loggingOut': 'Déconnexion...',
    'nav.logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'nav.cancel': 'Annuler',
    'nav.logoutTitle': 'Déconnexion',
    
    // Hero
    'hero.platform': 'La plateforme des collectifs de slam',
    'hero.title': 'GÉREZ VOS',
    'hero.title1': 'MOTS.',
    'hero.title2': 'VOS SCÈNES.',
    'hero.title3': 'VOS POÈTES.',
    'hero.description': 'Slam Net est la plateforme dédiée aux collectifs de slam poésie — gérez vos membres, organisez vos tournois, tirez au sort les passages et suivez les classements en temps réel.',
    'hero.createCollective': 'CRÉER MON COLLECTIF',
    'hero.watchDemo': 'VOIR UNE DÉMO',
    'hero.liveRanking': 'CLASSEMENT LIVE',
    'hero.tournamentInProgress': 'TOURNOI EN COURS',
    'hero.explore': 'EXPLORER',
    
    // Features
    'features': 'FONCTIONNALITÉS',
    'features.title': 'TOUT CE DONT',
    'features.title1': 'VOTRE COLLECTIF',
    'features.title2': 'A BESOIN.',
    'features.description': 'Une seule plateforme pour gérer la vie de votre collectif de slam — des membres aux podiums, en passant par chaque vers prononcé sur scène.',
    'feature01.title': 'GESTION DES MEMBRES',
    'feature01.description': 'Enregistrez chaque poète de votre collectif — nom, contact, biographie, historique de performances. Un annuaire complet, toujours à portée de main.',
    'feature01.detail': 'Profils détaillés · Historique · Statuts',
    'feature02.title': 'TOURNOIS ORGANISÉS',
    'feature02.description': 'Créez des tournois, définissez les règles, gérez les inscriptions — membres du collectif ou invités extérieurs. Chaque événement, de A à Z.',
    'feature02.detail': 'Multi-tours · Invités · Inscriptions en ligne',
    'feature03.title': 'TIRAGE AU SORT',
    'feature03.description': 'Le tirage au sort automatique décide de l\'ordre de passage à chaque tour. Transparent, impartial, sans friction.',
    'feature03.detail': 'Aléatoire certifié · Ronde par ronde · Export PDF',
    'feature04.title': 'NOTES & CLASSEMENTS',
    'feature04.description': 'Saisissez les notes des jurés en direct. Le classement se met à jour instantanément. La scène connaît son champion dès la dernière note tombée.',
    'feature04.detail': 'Notes en temps réel · Jury multiple · Podium',
    
    // How it works
    'howItWorks': 'COMMENT ÇA MARCHE',
    'howItWorks.title': 'DU COLLECTIF',
    'howItWorks.title1': 'AU PODIUM',
    'howItWorks.title2': 'EN 6 ÉTAPES.',
    'step01.title': 'Créez votre collectif',
    'step01.description': 'Inscrivez-vous en 2 minutes, nommez votre collectif et commencez à inviter vos poètes.',
    'step02.title': 'Enregistrez vos membres',
    'step02.description': 'Ajoutez chaque slammeur avec son profil complet. Ils peuvent aussi rejoindre via un lien d\'invitation.',
    'step03.title': 'Lancez un tournoi',
    'step03.description': 'Créez un tournoi, définissez les rounds, ouvrez les inscriptions aux membres et aux invités.',
    'step04.title': 'Tirage & passages',
    'step04.description': 'Déclenchez le tirage au sort. L\'ordre de passage est généré automatiquement pour chaque tour.',
    'step05.title': 'Saisissez les notes',
    'step05.description': 'Chaque juré note en direct. Le système calcule les moyennes et met à jour le classement.',
    'step06.title': 'Couronnez le champion',
    'step06.description': 'Le classement final est établi. Partagez le podium, archivez l\'événement.',
    
    // CTA
    'cta.freeToStart': 'GRATUIT POUR COMMENCER',
    'cta.title': 'VOTRE COLLECTIF',
    'cta.title1': 'MÉRITE UNE',
    'cta.title2': 'VRAIE SCÈNE.',
    'cta.description': 'Rejoignez les collectifs de slam qui organisent leurs événements avec Slam Net. Inscription gratuite, aucune carte requise.',
    'cta.createFreeAccount': 'CRÉER MON COMPTE GRATUIT',
    
    // Auth modals
    'auth.login': 'CONNEXION',
    'auth.signup': 'INSCRIPTION',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.emailPlaceholder': 'votre@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signIn': 'Se connecter',
    'auth.signingIn': 'Connexion...',
    'auth.createAccount': 'Créer mon compte',
    'auth.creatingAccount': 'Inscription...',
    'auth.collectiveName': 'Nom du collectif',
    'auth.collectiveNamePlaceholder': 'Nom de votre collectif',
    'auth.city': 'Ville',
    'auth.cityPlaceholder': 'Votre ville',
    'auth.noAccount': 'Pas encore de compte?',
    'auth.hasAccount': 'Déjà un compte?',
    'auth.signUp': 'S\'inscrire',
    'auth.loginLink': 'Se connecter',
    'auth.emailPasswordRequired': 'Email et mot de passe requis',
    'auth.invalidEmail': 'Format d\'email invalide',
    'auth.allFieldsRequired': 'Tous les champs doivent être remplis',
    'auth.passwordMinLength': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'auth.loginSuccess': 'Connexion réussie',
    'auth.signupSuccess': 'Compte créé avec succès',
    'auth.loginError': 'Erreur lors de la connexion',
    'auth.signupError': 'Erreur lors de l\'inscription',
    'auth.loggingIn': 'Connexion en cours...',
    
    // Footer
    'footer.copyright': '© 2026 SLAM NET · TOUS DROITS RÉSERVÉS',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'CGU',
    'footer.contact': 'Contact',
    
    // Privacy page
    'privacy.title': 'CONFIDENTIALITÉ',
    'privacy.dataCollection.title': 'Collecte des données',
    'privacy.dataCollection.description': 'Slam Net collecte uniquement les données nécessaires au fonctionnement de la plateforme, notamment les informations de compte, les données des collectifs et les statistiques de performance.',
    'privacy.dataUsage.title': 'Utilisation des données',
    'privacy.dataUsage.description': 'Vos données sont utilisées pour vous permettre de gérer votre collectif, d\'organiser des tournois et de suivre les performances des poètes. Nous ne vendons pas vos données à des tiers.',
    'privacy.hosting.title': 'Hébergement',
    'privacy.hosting.description': 'Toutes vos données sont hébergées sur des serveurs situés en France, conformément aux réglementations européennes de protection des données (RGPD).',
    'privacy.yourRights.title': 'Vos droits',
    'privacy.yourRights.description': 'Vous avez le droit d\'accéder, de modifier et de supprimer vos données personnelles à tout moment. Contactez-nous pour exercer ces droits.',
    
    // Terms page
    'terms.title': 'CONDITIONS GÉNÉRALES',
    'terms.platformUsage.title': 'Utilisation de la plateforme',
    'terms.platformUsage.description': 'Slam Net est destiné aux collectifs de slam poésie pour organiser des événements et gérer leurs membres. Toute utilisation abusive ou frauduleuse entraînera la suppression du compte.',
    'terms.liability.title': 'Responsabilité',
    'terms.liability.description': 'Slam Net ne peut être tenu responsable des dommages directs ou indirects résultant de l\'utilisation de la plateforme. Les utilisateurs sont responsables du contenu qu\'ils publient.',
    'terms.intellectualProperty.title': 'Propriété intellectuelle',
    'terms.intellectualProperty.description': 'Les créations originales (poèmes, textes, performances) restent la propriété de leurs auteurs. Slam Net ne revendique aucun droit sur le contenu créé par les utilisateurs.',
    'terms.modification.title': 'Modification des conditions',
    'terms.modification.description': 'Slam Net se réserve le droit de modifier ces conditions générales à tout moment. Les utilisateurs seront informés des changements importants.',
    
    // Contact page
    'contact.title': 'CONTACT',
    'contact.email.title': 'Email',
    'contact.phone.title': 'Téléphone',
    'contact.address.title': 'Adresse',
    
    // Dashboard
    'dashboard.title': 'DASHBOARD',
    'dashboard.needLogin': 'Vous devez être connecté pour accéder à cette page',
    'dashboard.members': 'Membres',
    'dashboard.tournaments': 'Tournois',
    'dashboard.performances': 'Performances',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.organizeTournament': 'Organiser un nouveau tournoi',
    'dashboard.organizeTournamentDesc': 'Créer et configurer un tournoi',
    'dashboard.inviteMember': 'Inviter un membre',
    'dashboard.inviteMemberDesc': 'Ajouter un nouveau poète au collectif',
    'dashboard.viewStats': 'Voir les statistiques',
    'dashboard.viewStatsDesc': 'Analytiques détaillées du collectif',
    'dashboard.activeTournaments': 'Tournois en cours',
    'dashboard.noActiveTournaments': 'Aucun tournoi en cours',
    
    // Membres
    'membres.title': 'MEMBRES',
    'membres.subtitle': 'NOS POÈTES.',
    'membres.description': 'Gérez les membres de votre collectif',
    'membres.addMember': 'Ajouter un membre',
    'membres.search': 'Rechercher un membre...',
    'membres.loading': 'Chargement...',
    'membres.noMembers': 'Aucun membre dans votre collectif',
    'membres.noMembersFound': 'Aucun membre trouvé',
    'membres.addFirstMember': 'Ajouter votre premier membre',
    'membres.deleteSuccess': 'Membre supprimé avec succès',
    'membres.deleteError': 'Erreur lors de la suppression du membre',
    'membres.bornOn': 'Né(e) le',
    
    // Tournois
    'tournois.title': 'TOURNOIS',
    'tournois.subtitle': 'NOS TOURNOIS.',
    'tournois.description': 'Gérez les tournois de votre collectif',
    'tournois.addTournament': 'Ajouter un tournoi',
    'tournois.loading': 'Chargement des tournois...',
    'tournois.needLogin': 'Vous devez être connecté pour accéder à cette page',
    'tournois.noTournament': 'Aucun tournoi',
    'tournois.noTournamentDesc': 'Vous n\'avez pas encore créé de tournoi. Commencez par organiser votre premier événement !',
    'tournois.createTournament': 'Créer un tournoi',
    'tournois.createSuccess': 'Tournoi créé avec succès',
    'tournois.updateSuccess': 'Tournoi modifié avec succès',
    'tournois.deleteSuccess': 'Tournoi supprimé avec succès',
    'tournois.deleteError': 'Erreur lors de la suppression du tournoi',
    'tournois.manage': 'Gérer le tournoi',
    'tournois.manageShort': 'Gérer',
    'tournois.juror': 'juré',
    'tournois.jurors': 'jurés',
    
    // Common buttons and actions
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.cancel': 'Annuler',
    'common.create': 'Créer',
    'common.save': 'Enregistrer',
    'common.creating': 'Création...',
    'common.updating': 'Mise à jour...',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.stageName': 'Nom de scène',
    'common.add': 'Ajouter',
    'common.addPhoto': 'Ajouter',
    'common.loading': 'Chargement...',
    'common.loadingInfo': 'Chargement des informations...',
    
    // Create Member Dialog
    'createMember.title': 'Nouveau membre',
    'createMember.lastName': 'Nom *',
    'createMember.firstName': 'Prénom *',
    'createMember.pseudo': 'Pseudo *',
    'createMember.email': 'Email *',
    'createMember.dateOfBirth': 'Date de naissance *',
    'createMember.address': 'Adresse *',
    'createMember.createdSuccess': 'Membre créé avec succès',
    'createMember.createError': 'Erreur lors de la création du membre',
    
    // Update Member Dialog
    'updateMember.title': 'Modifier le membre',
    'updateMember.lastName': 'Nom',
    'updateMember.firstName': 'Prénom',
    'updateMember.pseudo': 'Pseudo',
    'updateMember.email': 'Email',
    'updateMember.dateOfBirth': 'Date de naissance',
    'updateMember.address': 'Adresse',
    'updateMember.preview': 'Prévisualisation',
    'updateMember.photoUploadSuccess': 'Photo uploadée avec succès',
    'updateMember.photoUploadError': 'Erreur lors de l\'upload de la photo',
    'updateMember.loadingInfo': 'Chargement des informations...',
    'updateMember.updatedSuccess': 'Membre mis à jour avec succès',
    'updateMember.updateError': 'Erreur lors de la mise à jour du membre',
    
    // Create Tournament Dialog
    'createTournoi.title': 'Nouveau tournoi',
    'createTournoi.name': 'Nom du tournoi *',
    'createTournoi.namePlaceholder': 'Ex: Grand Slam de Paris',
    'createTournoi.location': 'Lieu *',
    'createTournoi.locationPlaceholder': 'Ex: Café de la Gare',
    'createTournoi.date': 'Date *',
    'createTournoi.time': 'Heure *',
    'createTournoi.juryCount': 'Nombre de jurés *',
    'createTournoi.duration': 'Durée par performance (optionnel)',
    'createTournoi.durationFormat': 'Format : minutes:secondes (ex: 3:00)',
    'createTournoi.enableDraw': 'Activer le tirage au sort des participants',
    'createTournoi.posterUrl': 'URL de l\'affiche (optionnel)',
    'createTournoi.posterPlaceholder': 'https://exemple.com/affiche.jpg',
    'createTournoi.allFieldsRequired': 'Tous les champs requis doivent être remplis',
    'createTournoi.minJuryError': 'Le nombre de jurés doit être au moins 1',
    'createTournoi.createError': 'Erreur lors de la création du tournoi',
    'createTournoi.min': 'Min',
    'createTournoi.sec': 'Sec',
    
    // Delete dialogs
    'deleteMember.title': 'Supprimer le membre',
    'deleteMember.message': 'Êtes-vous sûr de vouloir supprimer ce membre ? Cette action est irréversible.',
    'deleteTournoi.title': 'Supprimer le tournoi',
    'deleteTournoi.message': 'Êtes-vous sûr de vouloir supprimer le tournoi "{name}" ? Cette action est irréversible.',
    
    // Tournoi Gestion Layout
    'tournoiGestion.tournament': 'TOURNOI',
    'tournoiGestion.loading': 'Chargement du tournoi...',
    'tournoiGestion.notFound': 'Tournoi non trouvé',
    'tournoiGestion.backToTournois': 'Retour aux tournois',
    'tournoiGestion.menu': 'Menu',
    'tournoiGestion.closeMenu': 'Fermer le menu',
    'tournoiGestion.participants': 'Participants',
    'tournoiGestion.performances': 'Performances',
    'tournoiGestion.ranking': 'Classement',
    'tournoiGestion.settings': 'Paramètres',
    
    // Tournoi Participants
    'tournoiParticipants.title': 'Participants',
    'tournoiParticipants.addParticipant': 'Ajouter un participant',
    'tournoiParticipants.loading': 'Chargement des participants...',
    'tournoiParticipants.noParticipants': 'Aucun participant pour le moment',
    'tournoiParticipants.loadingError': 'Erreur lors du chargement des participants',
    'tournoiParticipants.removeSuccess': 'Participant retiré avec succès',
    'tournoiParticipants.removeError': 'Erreur lors du retrait du participant',
    'tournoiParticipants.removeTitle': 'Retirer le participant',
    'tournoiParticipants.removeMessage': 'Êtes-vous sûr de vouloir retirer ce participant du tournoi ?',
    'tournoiParticipants.remove': 'Retirer',
    'tournoiParticipants.member': 'Membre',
    'tournoiParticipants.guest': 'Invité',
    'tournoiParticipants.delete': 'Supprimer',
    
    // Add Participant Dialog
    'addParticipant.title': 'Ajouter des participants',
    'addParticipant.membersTab': 'Membre du collectif',
    'addParticipant.guestsTab': 'Invité',
    'addParticipant.searchMember': 'Rechercher un membre...',
    'addParticipant.noMemberFound': 'Aucun membre trouvé',
    'addParticipant.noMemberAvailable': 'Aucun membre disponible',
    'addParticipant.membersCount': 'membres',
    'addParticipant.inscribed': 'inscrit',
    'addParticipant.pseudo': 'Pseudo',
    'addParticipant.pseudoRequired': 'Le pseudo est requis',
    'addParticipant.selectMember': 'Veuillez sélectionner un membre',
    'addParticipant.alreadyInscribed': 'Ce membre est déjà inscrit au tournoi',
    'addParticipant.loadingMembers': 'Erreur lors du chargement des membres',
    'addParticipant.registering': 'Inscription...',
    'addParticipant.register': 'Inscrire',
    'addParticipant.memberInscribed': 'Inscrit',
    'addParticipant.finish': 'Terminer',
    'addParticipant.registerSuccess': 'Membre inscrit au tournoi avec succès',
    'addParticipant.registerError': 'Erreur lors de l\'inscription au tournoi',
    'addParticipant.guestPlaceholder': 'Entrez le pseudo de l\'invité',
    'addParticipant.guestSuccess': 'Invité inscrit au tournoi avec succès',
    'addParticipant.guestError': 'Erreur lors de l\'inscription de l\'invité',
    
    // Tournoi Performances
    'tournoiPerformances.title': 'Performances',
    'tournoiPerformances.addPerformance': 'Ajouter une performance',
    'tournoiPerformances.loading': 'Chargement des performances...',
    'tournoiPerformances.noPerformances': 'Aucune performance pour le moment',
    'tournoiPerformances.deleteTitle': 'Supprimer la performance',
    'tournoiPerformances.deleteMessage': 'Êtes-vous sûr de vouloir supprimer cette performance ?',
    'tournoiPerformances.createSuccess': 'Performance créée avec succès',
    'tournoiPerformances.createError': 'Erreur lors de la création de la performance',
    'tournoiPerformances.deleteSuccess': 'Performance supprimée avec succès',
    'tournoiPerformances.deleteError': 'Erreur lors de la suppression de la performance',
    'tournoiPerformances.terminatedSuccess': 'Performance terminée avec succès',
    'tournoiPerformances.terminateError': 'Erreur lors de la terminaison de la performance',
    'tournoiPerformances.selectParticipant': 'Veuillez sélectionner un participant',
    'tournoiPerformances.participantNotFound': 'Participant non trouvé',
    'tournoiPerformances.noPerformanceSelected': 'Aucune performance sélectionnée',
    'tournoiPerformances.mustBeTerminated': 'Cette performance doit être terminée avant de pouvoir ajouter des notes',
    'tournoiPerformances.selectTerminated': 'Sélectionnez une performance terminée pour ajouter des notes',
    'tournoiPerformances.invalidNote': 'La valeur doit être un nombre entre 0 et 10',
    'tournoiPerformances.notesRequired': 'Vous devez ajouter exactement {nb} notes (nombre de jurys)',
    'tournoiPerformances.notesSaved': 'Notes enregistrées avec succès',
    'tournoiPerformances.saveError': 'Erreur lors de l\'enregistrement des notes',
    'tournoiPerformances.noteUpdated': 'Note mise à jour avec succès',
    'tournoiPerformances.updateNoteError': 'Erreur lors de la mise à jour de la note',
    'tournoiPerformances.loadingPerformances': 'Erreur lors du chargement des performances',
    'tournoiPerformances.loadingParticipants': 'Erreur lors du chargement des participants',
    'tournoiPerformances.createPerformance': 'Créer une performance',
    'tournoiPerformances.cancel': 'Annuler',
    'tournoiPerformances.create': 'Créer',
    'tournoiPerformances.start': 'Démarrer',
    'tournoiPerformances.play': 'Play',
    'tournoiPerformances.pause': 'Pause',
    'tournoiPerformances.finish': 'Terminer',
    'tournoiPerformances.recording': 'Enregistrement...',
    'tournoiPerformances.duration': 'Durée',
    'tournoiPerformances.score': 'Note',
    'tournoiPerformances.timer': 'Chronomètre',
    'tournoiPerformances.noCurrentPerformance': 'Aucune performance en cours',
    'tournoiPerformances.addNotes': 'Ajouter des notes et pénalités',
    'tournoiPerformances.notes': 'Notes',
    'tournoiPerformances.penalties': 'Pénalités',
    'tournoiPerformances.notePlaceholder': 'Note (ex: 8,5)',
    'tournoiPerformances.penaltyPlaceholder': 'Pénalité (ex: 1,5)',
    'tournoiPerformances.add': 'Ajouter',
    'tournoiPerformances.notesToRecord': 'Notes à enregistrer',
    'tournoiPerformances.penaltiesToRecord': 'Pénalités à enregistrer',
    'tournoiPerformances.maxNotesReached': 'Nombre maximum de notes atteint ({nb} jurys)',
    'tournoiPerformances.remove': 'Retirer',
    'tournoiPerformances.restore': 'Rétablir',
    'tournoiPerformances.save': 'Enregistrer',
    'tournoiPerformances.existingNotes': 'Notes et pénalités existantes',
    'tournoiPerformances.listTab': 'Liste',
    'tournoiPerformances.inProgressTab': 'En cours',
    'tournoiPerformances.notesTab': 'Note',
    'tournoiPerformances.draw': 'Tirage au sort',
    'tournoiPerformances.ready': 'Prêt',
    'tournoiPerformances.inProgress': 'En cours',
    'tournoiPerformances.paused': 'En pause',
    'tournoiPerformances.completed': 'Terminée',
    'tournoiPerformances.notDefined': 'Non défini',
    'tournoiPerformances.participant': 'Participant',
    'tournoiPerformances.unknown': 'Inconnu',
    'tournoiPerformances.drawing': 'TIRAGE EN COURS...',
    'tournoiPerformances.winnerSelected': 'PARTICIPANT SÉLECTIONNÉ!',
    'tournoiPerformances.spin': 'Tourner la roulette',
    'tournoiPerformances.goodLuck': 'Bonne chance à tous!',
    'tournoiPerformances.availableCount': 'Participants disponibles',
    'tournoiPerformances.currentMax': 'Max de performances actuel',
    'tournoiPerformances.nextRoundReady': '⭐ Nouveau tour prêt! ⭐',
    'tournoiPerformances.allParticipantsEqual': 'Tous les participants ont le même nombre de performances',
    'tournoiPerformances.allHavePerformances': 'Chacun a {count} performance(s)',
    'tournoiPerformances.startNextRound': 'Commencer le tour suivant',
    'tournoiPerformances.lastParticipant': '⚡ Dernier participant disponible! ⚡',
    'tournoiPerformances.confirm': 'Confirmer la création',
    'tournoiPerformances.redraw': 'Recommencer',
    
    // Tournoi Classement
    'tournoiClassement.title': 'Classement',
    'tournoiClassement.loading': 'Chargement du classement...',
    'tournoiClassement.noRanking': 'Aucun classement pour le moment',
    'tournoiClassement.summary': 'Résumé',
    'tournoiClassement.participants': 'Participants',
    'tournoiClassement.average': 'Moyenne',
    'tournoiClassement.maxRounds': 'Rounds max',
    'tournoiClassement.loadingError': 'Erreur lors du chargement des données',
    
    // Tournoi Paramètres
    'tournoiParametres.title': 'Paramètres du tournoi',
    'tournoiParametres.durationSection': 'Durée de performance',
    'tournoiParametres.maxDurationLabel': 'Durée maximale par performance (min:sec)',
    'tournoiParametres.durationPlaceholder': '03:00',
    'tournoiParametres.durationFormat': 'Format attendu : min:sec (ex: 03:00 pour 3 minutes)',
    'tournoiParametres.jurySection': 'Jury',
    'tournoiParametres.juryCountLabel': 'Nombre de membres du jury',
    'tournoiParametres.juryCountDescription': 'Nombre de jurés qui noteront chaque performance',
    'tournoiParametres.drawSection': 'Tirage au sort',
    'tournoiParametres.enableDraw': 'Activer le tirage au sort',
    'tournoiParametres.enableDrawDescription': 'Permet de sélectionner aléatoirement le participant lors de la création d\'une performance',
    'tournoiParametres.saving': 'Enregistrement...',
    'tournoiParametres.save': 'Enregistrer',
     'tournoiParametres.updateSuccess': 'Paramètres mis à jour avec succès',
     'tournoiParametres.updateError': 'Erreur lors de la mise à jour des paramètres',
     
     // Statistics
     'statistics.title': 'Statistiques',
     'statistics.loading': 'Chargement des statistiques...',
     'statistics.participantStats.title': 'Statistiques du Participant',
     'statistics.participantStats.analysis': 'Analyse de Performance',
    'statistics.participantStats.details': 'Détails par Round',
    'statistics.participantStats.notes': 'Notes',
     'statistics.participantStats.penalties': 'Pénalités',
     'statistics.participantStats.scoreEvolution': 'Évolution des Scores',
     'statistics.participantStats.scoreVsAverage': 'Score vs Moyenne Jury',
      'statistics.participantStats.penaltiesByRound': 'Pénalités par Round',
      'statistics.participantStats.noNotes': 'Aucune note',
      'statistics.participantStats.noPerformances': 'Aucune performance enregistrée',
      'statistics.participantStats.rounds': 'Rounds',
      'statistics.participantStats.totalPoints': 'Total Points',
      'statistics.participantStats.average': 'Moyenne',
      'statistics.participantStats.best': 'Meilleur',
      'statistics.globalStats.title': 'Statistiques Globales',
     'statistics.globalStats.tournaments': 'Tournois',
     'statistics.globalStats.performances': 'Performances',
     'statistics.globalStats.totalPoints': 'Total Points',
     'statistics.globalStats.globalAverage': 'Moyenne Globale',
     'statistics.globalStats.analysis': 'Analyse de Performance',
     'statistics.globalStats.tournamentComparison': 'Comparaison par Tournoi',
     'statistics.globalStats.scoreDistribution': 'Répartition des Performances',
     'statistics.globalStats.consistency': 'Taux de Consistance',
     'statistics.globalStats.standardDeviation': 'Écart-type',
     'statistics.globalStats.performanceHistory': 'Historique par Tournoi',
     'statistics.globalStats.excellent': 'Excellent (>8)',
     'statistics.globalStats.good': 'Bon (6-8)',
     'statistics.globalStats.average': 'Moyen (<6)',
     'statistics.globalStats.meanEvolution': 'Évolution des Moyennes par Tournoi',
     'statistics.globalStats.noTournaments': 'Aucun tournoi enregistré',
     'statistics.globalStats.bestPerformance': 'Meilleure Performance',
     'statistics.globalStats.worstPerformance': 'Pire Performance',
     'statistics.globalStats.total': 'Total',
     'statistics.globalStats.best': 'Meilleur',
     'statistics.memberProfile.loading': 'Chargement du membre...',
     'statistics.memberProfile.notFound': 'Membre non trouvé',
     'statistics.memberProfile.backToMembers': 'Retour aux membres',
     'statistics.memberProfile.viewProfile': 'Voir profil',
     
     // Slam Poetry
     'slamPoetry.title': 'SLAM POÉSIE ?',
     'slamPoetry.whatsTitle': 'Qu\'est-ce que le Slam ?',
     'slamPoetry.whatsP1': 'Un slam est, historiquement, une compétition de poésie. C\'est une poésie déclamée dans des espaces publics (dans la rue, un bar...) ou dans un lieu de spectacle (dans une salle de concert, un théâtre...), avec ou sans accompagnement musical. Le slam appartient au genre de la poésie engagée, dont il renouvelle les codes.',
     'slamPoetry.whatsP2': 'Le vocabulaire est familier (argot, verlan, néologismes) et le choix des mots est au service de la rythmique. Les jeux de mots et de sonorités sont fréquents (paronymes, rimes, synonymes).',
     'slamPoetry.whatsP3': 'Le slam se situe entre la diction et le chant. L\'éventuelle partie instrumentale est au service du texte et ne le couvre pas. Les instruments sont peu nombreux et accompagnent la voix.',
     'slamPoetry.historyTitle': 'Histoire',
     'slamPoetry.historyP1': 'Né d\'une idée du poète américain Marc Smith, en 1986, le slam a comme but de rendre les lectures de poèmes à la fois moins élitistes et moins ennuyeuses. Le slam prévoit des règles minimales, laissant une grande liberté aux poètes à l\'intérieur de ces règles de base.',
     'slamPoetry.historyP2': 'Les premiers événements de slam européens apparaissent en 1993. En France, le slam, en tant que genre ou scène spécifique, n\'apparaît que dans les années 1990, et plus particulièrement en 1995 avec la réunion d\'un noyau dur (Nada, Joël Barazer, MC Clean, Pilote le Hot) mêlant poètes et "performeurs" dans un bar de Pigalle, rue André Antoine – le Club-Club.',
     'slamPoetry.historyP3': 'En 2006, sort "Midi 20", premier album de spoken word de Grand Corps Malade, slameur plusieurs fois vainqueur des tournois Bouchazoreill\'slam, qui porte un coup de projecteur supplémentaire sur le mouvement français.',
     'slamPoetry.historyP4': 'En 2009, sous l\'impulsion de différentes associations françaises, se constitue "La Ligue Slam de France". Grand Corps Malade en est le membre d\'honneur et Marc Smith apporte son soutien dès sa création. En 2020 la Ligue fédère plus de 50 associations dans toute la France.',
     'slamPoetry.rulesTitle': 'Règles du Slam',
     'slamPoetry.rulesIntro': 'Même si le slam de poésie est souvent décrit comme un moyen de liberté d\'expression, le spectacle est structuré par des règles qui sont généralement les suivantes :',
     'slamPoetry.rule1': 'Les inscriptions sont ouvertes à tous auprès du présentateur',
     'slamPoetry.rule2': 'On peut passer seul ou à plusieurs',
     'slamPoetry.rule3': 'Le texte doit être original, c\'est-à-dire écrit par le slameur lui-même',
     'slamPoetry.rule4': 'La durée de la performance est généralement limitée à 3 minutes',
     'slamPoetry.rule5': 'L\'utilisation d\'accessoires (costumes, instruments de musique, décors) n\'est pas autorisée',
     'slamPoetry.rule6': 'Les spectateurs composent un jury qui note chaque performance',
     'slamPoetry.rule7': 'Les notes les plus hautes et les plus basses sont souvent éliminées',
     'slamPoetry.rule8': 'Les slameurs sont notés sur différents critères : l\'écriture, l\'interprétation, et la connexion avec le public',
     'slamPoetry.valuesTitle': 'Les valeurs du Slam',
     'slamPoetry.valuesP1': 'Le slam est une forme de lecture poétique considérée comme un mouvement d\'expression populaire, initialement en marge des circuits artistiques traditionnels, aujourd\'hui largement reconnu et médiatisé.',
     'slamPoetry.valuesP2': 'C\'est un art du spectacle oral et scénique, focalisé sur le verbe et l\'expression brute avec une grande économie de moyens, un lien entre écriture et performance.',
     'slamPoetry.valuesP3': 'Si des poètes, en particulier issus de la mouvance hip-hop, le revendiquent comme issu de la rue ainsi que le rap à ses débuts, il est néanmoins pratiqué par des poètes de tous styles, de tous milieux sociaux, en ville comme à la campagne.',
     'slamPoetry.valuesP4': 'Marc Smith aura relancé la prise de parole poétique sur la place publique et à l\'échelle planétaire. Il incombe désormais à chacun d\'avoir les mots pour se dire.',
     'slamPoetry.worldTitle': 'Slam dans le monde',
     'slamPoetry.worldIntro': 'Le slam s\'est développé dans de nombreux pays francophones et non francophones :',
     'slamPoetry.worldFrance': '<strong>France :</strong> Le mouvement est particulièrement actif avec la Ligue Slam de France, le Grand Slam National, et la Coupe du Monde de Slam.',
     'slamPoetry.worldBelgium': '<strong>Belgique :</strong> Les premières plateformes apparaissent en 2001 à Bruxelles, avec des scènes permanentes à Mons, Namur et Charleroi.',
     'slamPoetry.worldSwitzerland': '<strong>Suisse romande :</strong> Le slam apparaît en 2002 à Genève, avec des scènes à Lausanne, Fribourg et Neuchâtel.',
     'slamPoetry.worldQuebec': '<strong>Québec :</strong> La scène slam proprement dite est née en 2006 avec les soirées Slamontréal à Montréal.',
      'slamPoetry.worldIndianOcean': '<strong>Océan Indien :</strong> Le slam est introduit en 2002 par Stefan Hart de Keating, d\'abord à l\'île Maurice, puis à La Réunion, Madagascar, Mayotte et Rodrigues.',
      
      // Profile
      'profile.title': 'PROFIL',
      'profile.myProfile': 'MON PROFIL.',
      'profile.description': 'Gérez les informations de votre collectif',
      'profile.mustBeLoggedIn': 'Vous devez être connecté pour accéder à cette page',
      'profile.loadingError': 'Erreur de chargement du profil',
      'profile.edit': 'Modifier',
      'profile.uploadInProgress': 'Upload en cours...',
      'profile.collectiveName': 'Nom du collectif',
      'profile.city': 'Ville',
      'profile.email': 'Email',
      'profile.cancel': 'Annuler',
      'profile.saving': 'Enregistrement...',
      'profile.save': 'Enregistrer',
      'profile.memberSince': 'Membre depuis',
      'profile.photoUpdated': 'Photo mise à jour avec succès',
      'profile.photoUploadError': 'Erreur lors de l\'upload de la photo',
      'profile.updated': 'Profil mis à jour avec succès',
      'profile.updateError': 'Erreur lors de la mise à jour du profil',
      'profile.uploadError': 'Erreur lors de l\'upload',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'fr') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}